### ISSUE TITLE
Should rdf-vocab be offered to ruby-rdf?

### ISSUE THREAD

**Issue by dchandekstark** [projecthydra-labs/rdf-vocab#20]
In #19, @gkellogg mentioned this as a possibility, so I wanted to get ProjectHydra community feedback.  As pointed out in #19, it would require a license change. 

/cc @no-reply @jeremyf @jcoyne @mjgiarlo @jpstroop @acoburn @awead

**Comment by dchandekstark** [comment]
Closing with no action. Please re-open to re-raise question.

**Comment by gkellogg** [comment]
When we last looked at this, we were waiting for a license change to [UNLICENSE](http://unlicense.org/). There are also a couple of technical changes needed, mostly to lazy-load the vocabulary, rather than do a require of each one when this gem is loaded; that could be quite costly as the number of vocabularies is added.

RDF.rb does this by creating an autoload for each vocabulary, and a hard load if `Vocabulary.each` is called.

If the license on the gem is changed to UNLICENSE, this would require a dedication for any significant change or portion of this (trivial changes aren't necessary); see https://github.com/ruby-rdf/rdf/blob/develop/README.md#contributing.

To do this, we'd like to see the license terms changed, the repo moved to http://github.com/ruby-rdf/rdf-vocab, and push rights to rubygems.org updated to allow selected core-committers to release new versions of the gem; of course, original members of the gem retain all administrative rights.

/cd @bendiken

**Comment by dchandekstark** [comment]
@gkellogg Thanks for revisiting this issue. I will spin off an issue to do the lazy-loading.  As to the question of license change and move to ruby-rdf, I need to consult the Hydra community and current project contributors.  Stay tuned.

/cc @acoburn @mjgiarlo

**Comment by acoburn** [comment]
@dchandekstark regarding a possible license and org change, that sounds like a great item for next week's hydra-tech call.

**Comment by dchandekstark** [comment]
Decision made in the affirmative. See https://wiki.duraspace.org/display/hydra/Hydra+Tech+Call+2015-03-18.
